# Pokemon Data

In [1]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import datetime
import seaborn as sns
import plotly as py
from scipy.stats import norm

import os
%matplotlib inline

In [2]:
# Read in all the pokemon data to a dataframe
path = os.path.join(os.getcwd(),"..","data","","pokemon.csv")
data = pd.read_csv(path, index_col='name')

In [11]:
data.sample(5)

,abilities,against_bug,against_dark,against_dragon,against_electric,against_fairy,against_fight,against_fire,against_flying,against_ghost,...,percentage_male,pokedex_number,sp_attack,sp_defense,speed,type1,type2,weight_kg,generation,is_legendary
name,,,,,,,,,,,,,,,,,,,,,
Hitmonchan,"['Keen Eye', 'Iron Fist', 'Inner Focus']",0.5,0.5,1.0,1.0,2.0,1.0,1.0,2.0,1.0,...,100.0,107,35,110,76,fighting,NaN,50.2,1,0
Roselia,"['Natural Cure', 'Poison Point', 'Leaf Guard']",1.0,1.0,1.0,0.5,0.5,0.5,2.0,2.0,1.0,...,50.0,315,100,80,65,grass,poison,2.0,3,0
Porygon2,"['Trace', 'Download', 'Analytic']",1.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,0.0,...,NaN,233,105,95,60,normal,NaN,32.5,2,0
Furfrou,['Fur Coat'],1.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,0.0,...,50.0,676,65,90,102,normal,NaN,28.0,6,0
Gulpin,"['Liquid Ooze', 'Sticky Hold', 'Gluttony']",0.5,1.0,1.0,1.0,0.5,0.5,1.0,1.0,1.0,...,50.0,316,43,53,40,poison,NaN,10.3,3,0

In [13]:
", ".join(data.columns)

'abilities, against_bug, against_dark, against_dragon, against_electric, against_fairy, against_fight, against_fire, against_flying, against_ghost, against_grass, against_ground, against_ice, against_normal, against_poison, against_psychic, against_rock, against_steel, against_water, attack, base_egg_steps, base_happiness, base_total, capture_rate, classfication, defense, experience_growth, height_m, hp, japanese_name, percentage_male, pokedex_number, sp_attack, sp_defense, speed, type1, type2, weight_kg, generation, is_legendary'

In [7]:
%matplotlib inline

In [10]:
interesting_columns = ["speed","base_egg_steps","attack","defense","sp_attack","sp_defense"]
data2 = data[interesting_columns]
data2.astype(float).head()

            speed  base_egg_steps  attack  defense  sp_attack  sp_defense
name
Bulbasaur    45.0          5120.0    49.0     49.0       65.0        65.0
Ivysaur      60.0          5120.0    62.0     63.0       80.0        80.0
Venusaur     80.0          5120.0   100.0    123.0      122.0       120.0
Charmander   65.0          5120.0    52.0     43.0       60.0        50.0
Charmeleon   80.0          5120.0    64.0     58.0       80.0        65.0